package pwalk

import (
	"io/fs"
	"os"

	"github.com/robdavid/pwalk/pkgs/assemble"
	"github.com/robdavid/pwalk/pkgs/path"
	"github.com/robdavid/pwalk/pkgs/walk"
	"github.com/robdavid/pwalk/pkgs/workpool"
)

type Workpool interface {
	Run(func())
	Wait()
}

// Config is a function that mutates the current walk configuration
type Config = walk.Config
type GenConfigData[T any] = walk.GenConfigData[T]

// WalkFn is the type of a function that is passed to [Walk] that is called with
// each path encountered when walking the directory tree, along with any error
// code and directory entry details. It has the following type signature:
//
//	func(path.Path, fs.DirEntry, error)
//
// It is called sequentially with entries in sorted order.
type WalkFn = assemble.WalkFn

// MappedWalkFn is the type of a function that is passed to [GenWalk] that is
// called with each path encountered when walking the directory tree, along with
// any error code, directory entry, details and a mapped value of type T
// generated by the preprocessing function provided to [GenWalk] of type
// [PreProcessFn]. It has the following type signature:
//
//	func(path.Path, fs.DirEntry, error, T)
//
// It is called sequentially with entries in sorted order.
type MappedWalkFn[T any] = assemble.MappedWalkFn[T]

// FilterFn represents a function that can be optionally provided to allow some
// files to be excluded from those being walked. It has the following signature:
//
//	func(path.Path, os.DirEntry, error) (FilterAction, error)
//
// It is passed the details of each directory entry as it is being read, and in
// response it should return a [FilterAction] plus an error. The former
// determines whether the file or associated directory is to be skipped, whereas
// the error will be passed through to the [WalkFn] or [MappedWalkFn] functions.
// If an error is encountered while reading a directory, the filter will be
// called with that directory path twice. The first time occurs as its name and
// metadata are being read, and always with an nil
// error. The second time is with the same path and the error encountered while
// reading it.
//
// The returned [FilterAction] value can have one of the possible values
// [FilterAccept], [FilterSkip] or [FilterSkipDir].
//
// This function is called concurrently in multiple goroutines as directories
// are being read in parallel, so it should be thread-safe.
type FilterFn = walk.FilterFn

const (
	// FilterAccept indicates the file entry is to be included.
	FilterAccept = walk.FilterAccept
	// FilterSkip indicates the file entry is to be excluded, whether it is a
	// file or a directory.
	FilterSkip = walk.FilterSkip
	// FilterSkipDir indicates that a directory should be replaced with an empty
	// directory. Typically the directory being replaced is the parent directory
	// of the current entry. The exceptions to this are if the current entry is
	// itself a directory and an error is being reported as a result of reading
	// that directory, or if the directory is the root directory. In these cases
	// the current entry is replaced by an empty directory. Errors are indicated
	// by a non-nil err argument passed to [FilterFn] or [PreProcessFn].
	FilterSkipDir = walk.FilterSkipDir
)

// FilterAction is returned as the result of the [FilterFn] function or
// [PreProcessFn] function. Possible values are [FilterAccept], [FilterSkip] or
// [FilterSkipDir].
type FilterAction = walk.FilterAction

// PreProcessFn is a type of generic function that may be provided to [GenWalk]
// which allows directory entries to be both transformed and filtered at the
// point they are being read. It has the following type signature:
//
//	func(path.Path, os.DirEntry, error) (T, FilterAction, error)
//
// Its semantics are similar to that of [FilterFn] with the additional feature
// that it can return a value of type T constructed by the function based on the
// entry being read. This value is then passed through to the walk function of
// type [MappedWalkFn] also passed to [GenWalk].
//
// This function is called concurrently in multiple goroutines as directories
// are being read in parallel, so it should be thread-safe.
type PreProcessFn[T any] = walk.PreProcessFn[T]

func runWalk[T any](config *walk.WalkConfig[T], p path.Path, ass *assemble.Assembly[T]) {
	d := walk.Read(config, p)
	ass.Sink(d)
	for _, entry := range d.Entries {
		if entry.IsDir() {
			config.Workpool.Run(func() {
				runWalk(config, d.Path.Append(entry.Name()), ass)
			})
		}
	}
}

func toMappedWalkFn(fn WalkFn) MappedWalkFn[walk.Void] {
	return func(p path.Path, ent fs.DirEntry, err error, void walk.Void) {
		fn(p, ent, err)
	}
}

func chainFilter[T any](filter FilterFn, preProcessor PreProcessFn[T]) PreProcessFn[T] {
	if filter == nil {
		return preProcessor
	} else if preProcessor == nil {
		return func(pth path.Path, ent os.DirEntry, err error) (T, FilterAction, error) {
			var zero T
			action, rerr := filter(pth, ent, err)
			return zero, action, rerr
		}
	} else {
		return func(pth path.Path, ent os.DirEntry, err error) (T, FilterAction, error) {
			action, rerr := filter(pth, ent, err)
			if action != walk.FilterAccept {
				var zero T
				return zero, action, rerr
			}
			return preProcessor(pth, ent, err)
		}
	}
}

// Walk traverses the directory tree rooted at the given path and calls fn for each
// file, directory, and error encountered. It walks the tree depth-first in deterministic
// (lexicographical) order.
//
// Parameters:
//   - root: the root directory path to start walking from
//   - fn: WalkFn callback invoked for each path; receives the path, an optional error, and dir entry details.
//     Files are delivered in a consistent depth-first sorted directory entry order.
//   - config: optional variadic configuration functions that can adjust walk behavior.
//
// Configuration functions:
//   - ConfigThreads(n): set the number of worker threads (default: runtime.NumCPU()). This option is
//     ignored if a user supplied workpool is provided.
//   - ConfigWorkpool(wp): provide a custom Workpool implementation (default: internal workpool created).
//   - ConfigFilter(f): supply a Filter function to accept or reject paths during traversal. This is called
//     while directories are being read, so expect it to be called concurrently in multiple goroutines.
//   - ConfigFilesystem(fs): override the default filesystem implementation (for testing or custom storage).
//
// If no config options are provided, Walk uses an internal workpool with thread count
// equal to the system's CPU count.
func Walk(root string, fn WalkFn, config ...Config) {
	GenWalk(root, nil, toMappedWalkFn(fn), config...)
}

// GenWalk traverses the directory tree rooted at the given path, optionally
// applies a mapping function to each entry, and then calls fn for each mapped
// result, error, and entry. This is useful for transforming directory entries
// into custom data structures or aggregating information (e.g., computing sums,
// building maps, etc.) during traversal. Note that the mpping function is
// called as the directories are being read, so it is called concurrently in
// multiple goroutines and should be thread-safe.
//
// Parameters:
//   - root: the root directory path to start walking from
//   - pre: a [PreProcessFn] function that is called for each file entry as it is being read. This function
//     is able to both filter entries, similar to the filter function available through config, and to
//     map each entry to a value of a different type. This type is the type parameter of this function and
//     GenWalk itself. This value is passed to each invocation of fn.
//   - fn: [MappedWalkFn] callback invoked for each entry with the map result; receives the path,
//     the mapped value, an optional error, and dir entry details. Files are delivered in
//     a consistent depth-first sorted directory entry order.
//   - config: optional variadic configuration functions that can adjust walk behavior.
//
// Configuration functions for config parameter:
//   - ConfigThreads(n): set the number of worker threads (default: runtime.NumCPU())
//   - ConfigWorkpool(wp): provide a custom Workpool implementation (default: internal workpool created)
//   - ConfigFilter(f): supply a Filter function to accept or reject paths during traversal. This is called
//     while directories are being read, so expect it to be called concurrently in multiple goroutines.
//   - ConfigFilesystem(fs): override the default filesystem implementation (for testing or custom storage)
//
// If no config options are provided, WalkAndMap uses an internal workpool with
// thread count equal to the system's CPU count. The mapping function (if
// provided) is called once per directory and its result is passed to fn along
// with all contained files and subdirectories.
func GenWalk[T any](root string, pre PreProcessFn[T], fn MappedWalkFn[T], config ...Config) {
	configData := walk.NewConfigData()
	for _, c := range config {
		c(configData)
	}
	if configData.Workpool == nil {
		wp := workpool.New(configData.Threads, 0)
		defer wp.Stop()
		configData.Workpool = wp
	}
	walkConfig := walk.WalkConfig[T]{
		ConfigData: *configData,
		GenConfigData: walk.GenConfigData[T]{
			PreProcessor: chainFilter(configData.Filter, pre),
		},
	}

	rootPath := path.New(root)
	rootEnt := walk.NewRootDirEntry(configData.Filesystem, rootPath)

	var mp T
	var action walk.FilterAction
	var err error

	if walkConfig.PreProcessor != nil {
		mp, action, err = walkConfig.PreProcessor(rootPath, rootEnt, nil)
	}
	ass := assemble.New(&walkConfig, mp, fn)
	defer ass.Close()

	switch action {
	case walk.FilterSkip:
		return
	case walk.FilterSkipDir:
		emptyDir := walk.Dir[T]{
			Path:    rootPath,
			Entries: []walk.DirEntry[T]{},
			Error:   err,
		}
		ass.Sink(&emptyDir)
		ass.Wait()
	default:
		configData.Workpool.Run(func() {
			runWalk(&walkConfig, path.New(root), ass)
		})
		configData.Workpool.Wait()
		ass.Wait()
	}
}
